name: Angular CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js (no cache since no lock file)
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0  
        with:
          node-version: 20.x

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build Angular app
      - name: Build Angular
        run: npm run build --if-present

      # Optional: Run tests
      - name: Run tests
        run: npm test --if-present
